/**
 * Advisor Reviews DB — Phase 4.3
 * Stores weekly retrospectives and proactive flags generated by Claude.
 * All functions are synchronous (better-sqlite3).
 */

const db = require('./index');

function initAdvisorTables() {
  db.exec(`
    CREATE TABLE IF NOT EXISTS advisor_reviews (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      week_of TEXT NOT NULL,
      summary TEXT NOT NULL,
      review_type TEXT NOT NULL DEFAULT 'weekly',
      has_unread_observation INTEGER DEFAULT 1,
      created_at TEXT DEFAULT (datetime('now'))
    )
  `);
  console.log('✅ Advisor reviews table initialized');
}

function saveAdvisorReview(data) {
  // data: { week_of, summary, review_type }
  db.prepare(`
    INSERT INTO advisor_reviews (week_of, summary, review_type, has_unread_observation, created_at)
    VALUES (?, ?, ?, 1, datetime('now'))
  `).run(data.week_of, data.summary, data.review_type || 'weekly');

  return db.prepare(`SELECT * FROM advisor_reviews WHERE rowid = last_insert_rowid()`).get();
}

function getAllAdvisorReviews() {
  return db.prepare(`SELECT * FROM advisor_reviews ORDER BY created_at DESC`).all();
}

function getAdvisorReview(id) {
  return db.prepare(`SELECT * FROM advisor_reviews WHERE id = ?`).get(id) || null;
}

function markReviewRead(id) {
  db.prepare(`UPDATE advisor_reviews SET has_unread_observation = 0 WHERE id = ?`).run(id);
}

function markAllReviewsRead() {
  db.prepare(`UPDATE advisor_reviews SET has_unread_observation = 0`).run();
}

function hasUnreadObservation() {
  const row = db.prepare(`SELECT COUNT(*) as count FROM advisor_reviews WHERE has_unread_observation = 1`).get();
  return row.count > 0;
}

function countProactiveThisWeek() {
  // Enforce max one proactive flag per week
  const weekAgo = new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString();
  const row = db.prepare(`
    SELECT COUNT(*) as count FROM advisor_reviews
    WHERE review_type = 'proactive' AND created_at > ?
  `).get(weekAgo);
  return row.count;
}

module.exports = {
  initAdvisorTables,
  saveAdvisorReview,
  getAllAdvisorReviews,
  getAdvisorReview,
  markReviewRead,
  markAllReviewsRead,
  hasUnreadObservation,
  countProactiveThisWeek,
};
