// seeds/waypoint-seed.js
// Auto-generated by: npm run export-seed — 2026-03-16T04:21:01.522Z
// To update: run `npm run export-seed` and commit the result.
module.exports = {
  projects: [
  {
    "name": "My Tasks",
    "color": "#818cf8",
    "icon": "📋"
  },
  {
    "name": "Work",
    "color": "#4ade80",
    "icon": "💼"
  },
  {
    "name": "Senex",
    "color": "#4ade80",
    "icon": "📁"
  },
  {
    "name": "CartQuoter",
    "color": "#818cf8",
    "icon": "📁"
  },
  {
    "name": "Backlog",
    "color": "#f87171",
    "icon": "📁"
  }
],

  outcomes: [
  {
    "project_name": "Work",
    "title": "Reusable Agent that responds to meeting requests",
    "description": null,
    "deadline": "2026-03-20",
    "priority": "medium",
    "status": "active"
  },
  {
    "project_name": "Backlog",
    "title": "Sponsorships OS Completed",
    "description": null,
    "deadline": null,
    "priority": "medium",
    "status": "active"
  },
  {
    "project_name": "My Tasks",
    "title": "VP marketing/sales at WIndow/Door",
    "description": null,
    "deadline": null,
    "priority": "medium",
    "status": "active"
  },
  {
    "project_name": "My Tasks",
    "title": "Mobile working",
    "description": null,
    "deadline": null,
    "priority": "medium",
    "status": "active"
  },
  {
    "project_name": "Backlog",
    "title": "AI qualifiers for Lead Score -- =gemini scoring the lead's ACTUAL qualifications (website, etv)",
    "description": null,
    "deadline": null,
    "priority": "medium",
    "status": "active"
  }
],

  actions: [
  {
    "outcome_title": "Reusable Agent that responds to meeting requests",
    "title": "Set up Gmail API service + polling cron",
    "energy_type": "deep",
    "done": false
  },
  {
    "outcome_title": "Reusable Agent that responds to meeting requests",
    "title": "Build Claude reply classifier (5 categories + structured output)",
    "energy_type": "deep",
    "done": false
  },
  {
    "outcome_title": "Reusable Agent that responds to meeting requests",
    "title": "Expand Google Calendar to multi-rep read + write + Meet",
    "energy_type": "deep",
    "done": false
  },
  {
    "outcome_title": "Reusable Agent that responds to meeting requests",
    "title": "Create booking orchestrator + state DB",
    "energy_type": "deep",
    "done": false
  },
  {
    "outcome_title": "Reusable Agent that responds to meeting requests",
    "title": "Wire up HubSpot logging + Slack alerts",
    "energy_type": "light",
    "done": false
  },
  {
    "outcome_title": "Reusable Agent that responds to meeting requests",
    "title": "Build status/control API routes",
    "energy_type": "light",
    "done": false
  },
  {
    "outcome_title": "Reusable Agent that responds to meeting requests",
    "title": "End-to-end test with real inbox",
    "energy_type": "deep",
    "done": false
  },
  {
    "outcome_title": "Sponsorships OS Completed",
    "title": "Jumpstart process",
    "energy_type": "light",
    "done": false
  },
  {
    "outcome_title": "Sponsorships OS Completed",
    "title": "Closing a deal in Hubspot",
    "energy_type": "light",
    "done": false
  },
  {
    "outcome_title": "Sponsorships OS Completed",
    "title": "Creating a sequence",
    "energy_type": "light",
    "done": false
  },
  {
    "outcome_title": "Mobile working",
    "title": "Chatup",
    "energy_type": "light",
    "done": false
  },
  {
    "outcome_title": "Mobile working",
    "title": "To dos CRUD",
    "energy_type": "light",
    "done": false
  },
  {
    "outcome_title": "Mobile working",
    "title": "Design overhaul",
    "energy_type": "light",
    "done": false
  }
],
};
