#!/usr/bin/env node
// scripts/export-seed.js
// Dumps current Railway DB state into seeds/waypoint-seed.js
//
// Required env vars:
//   WAYPOINT_API_URL  — e.g. https://your-app.up.railway.app
//   WAYPOINT_API_KEY  — your Waypoint API key
//
// Usage: npm run export-seed

'use strict';

const https = require('https');
const http  = require('http');
const path  = require('path');
const fs    = require('fs');

const API_URL = process.env.WAYPOINT_API_URL;
const API_KEY = process.env.WAYPOINT_API_KEY;

if (!API_URL) {
  console.error('❌  Missing env var: WAYPOINT_API_URL (e.g. https://yourapp.up.railway.app)');
  process.exit(1);
}
if (!API_KEY) {
  console.error('❌  Missing env var: WAYPOINT_API_KEY');
  process.exit(1);
}

function fetchJson(urlPath) {
  return new Promise((resolve, reject) => {
    const url      = new URL(urlPath, API_URL);
    const isHttps  = url.protocol === 'https:';
    const transport = isHttps ? https : http;

    const options = {
      hostname: url.hostname,
      port:     url.port || (isHttps ? 443 : 80),
      path:     url.pathname,
      headers:  { 'x-api-key': API_KEY },
    };

    const req = transport.get(options, (res) => {
      let raw = '';
      res.on('data', chunk => { raw += chunk; });
      res.on('end', () => {
        try { resolve(JSON.parse(raw)); }
        catch (e) { reject(new Error(`JSON parse error: ${e.message}\nBody: ${raw.slice(0, 200)}`)); }
      });
    });
    req.on('error', reject);
  });
}

async function main() {
  console.log(`📡 Fetching data from ${API_URL}...`);

  const [projectsRes, outcomesRes] = await Promise.all([
    fetchJson('/api/projects'),
    fetchJson('/api/outcomes'),
  ]);

  if (!projectsRes.success) throw new Error(`/api/projects failed: ${JSON.stringify(projectsRes)}`);
  if (!outcomesRes.success) throw new Error(`/api/outcomes failed: ${JSON.stringify(outcomesRes)}`);

  const projects = projectsRes.data.map(p => ({
    name:  p.name,
    color: p.color,
    icon:  p.icon,
  }));

  const outcomes = [];
  const actions  = [];

  for (const o of outcomesRes.data) {
    // Only seed active outcomes (archived ones accumulate naturally)
    if (o.status === 'archived') continue;

    outcomes.push({
      project_name: o.project_name,
      title:        o.title,
      description:  o.description  || null,
      deadline:     o.deadline     || null,
      priority:     o.priority     || 'medium',
      status:       o.status       || 'active',
    });

    for (const a of (o.actions || [])) {
      // Only seed incomplete actions — done ones are historical noise
      if (a.done) continue;
      actions.push({
        outcome_title: o.title,
        title:         a.title,
        energy_type:   a.energy_type || 'light',
        done:          false,
      });
    }
  }

  const seedContent =
`// seeds/waypoint-seed.js
// Auto-generated by: npm run export-seed — ${new Date().toISOString()}
// To update: run \`npm run export-seed\` and commit the result.
module.exports = {
  projects: ${JSON.stringify(projects, null, 2)},

  outcomes: ${JSON.stringify(outcomes, null, 2)},

  actions: ${JSON.stringify(actions, null, 2)},
};
`;

  const seedPath = path.join(__dirname, '../seeds/waypoint-seed.js');
  fs.writeFileSync(seedPath, seedContent, 'utf8');

  console.log(`✅ seeds/waypoint-seed.js updated:`);
  console.log(`   ${projects.length} project(s)`);
  console.log(`   ${outcomes.length} active outcome(s)`);
  console.log(`   ${actions.length} incomplete action(s)`);
  console.log('');
  console.log('Next: commit the updated seed file.');
  console.log('  git add seeds/waypoint-seed.js && git commit -m "chore: update seed data"');
}

main().catch(err => {
  console.error('❌ Export failed:', err.message);
  process.exit(1);
});
